export const APP_BAR_HEIGHT = 48
export const CONTROL_HEIGHT = 60

export const BREADCRUMB_HEIGHT = 20
export const BREADCRUMB_MARGIN_VERTICAL = 12
export const BREADCRUMB_TOTAL_HEIGHT = BREADCRUMB_HEIGHT + BREADCRUMB_MARGIN_VERTICAL * 2

export const PAGINATION_HEIGHT = 45
export const PAGINATION_HEIGHT_VERTICAL = 0
export const PAGINATION_TOTAL_HEIGHT = PAGINATION_HEIGHT + PAGINATION_HEIGHT_VERTICAL * 2

export const FOOTER = 25
export const BOTTOM_HEIGHT = 40

export const TABLE_HEIGHT = `calc(100vh - ${APP_BAR_HEIGHT}px - ${BREADCRUMB_TOTAL_HEIGHT}px - ${CONTROL_HEIGHT}px - ${BOTTOM_HEIGHT}px)`
export const TABLE_HEIGHT_INCLUDE_FOOTER = `calc(100vh - ${APP_BAR_HEIGHT}px - ${BREADCRUMB_TOTAL_HEIGHT}px - ${CONTROL_HEIGHT}px - ${PAGINATION_TOTAL_HEIGHT}px - ${BOTTOM_HEIGHT}px)`
export const TABLE_HEIGHT_BUDGET = `calc(100vh - ${APP_BAR_HEIGHT}px - ${BREADCRUMB_TOTAL_HEIGHT}px - ${CONTROL_HEIGHT}px - ${PAGINATION_TOTAL_HEIGHT}px - ${BOTTOM_HEIGHT}px - 35px)`
